# Generated by Django 5.2.5 on 2025-08-25 04:48

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('portada', models.ImageField(blank=True, upload_to='fotos/noticias/')),
                ('pruebas_en_pdf', models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/noticias')),
                ('video', models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/noticias', validators=[cloudinary_storage.validators.validate_video])),
            ],
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
