# Generated by Django 5.2.5 on 2025-08-25 16:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_noticia_delete_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='pruebas_en_pdf',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/noticias'),
        ),
    ]
