# Generated by Django 5.2.5 on 2025-08-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_alter_noticia_pruebas_en_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='pruebas_en_pdf',
            field=models.FileField(blank=True, upload_to='raw/noticias'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/noticias'),
        ),
    ]
